/**
 * This interface will help us to keep the waring and success messages over the project
 * @author Jagat Bandhu
 * @since 1.0.0
 */
export interface IMessages {
    checkInternetConnection: string,
    serverError: string,
    networkError: string,
    pleaseWait: string, 
    validUserName: string,
    validPassword: string,
    authentication: string,
    wentWrong: string,
    fetchUserDetails: string,
    warning: string,
    info: string,
    ok: string,
    cancel: string,
    differentUserLoginMsg: string,
    noStudentRecord: string,
    noCCHRecord: string,
    maxDate: string,
    dateTimeFormat: string,
    geoTagForPhoto: string,
    enableGeoLocation: string,
    uploadPhoto: string,
    recordSaved: string,
    recordUpdate: string,
    wrongCredential: string,
    noCredentialFound: string,
    update: string,
    newUpdate: string,
    updateMsg: string,
    updateInfoMsg: string,
    appPlayStoreUrl: string,
    logoutWarning: string,
    dataSyncMsg: string,
    somethingWentWrong: string,
    closeAppWarning: string,
    syncFromServer: string,
    syncToServer: string,
    sudentAttendance: string,
    cchAttendance: string,
    logout: string,
    syncDataMsg: string,
    noDataToSync: string,
    syncDataToServer: string,
    noActiveRecord: string,
    syncedRecord: string,
    failedRecord: string,
    syncedRecordForCch: string,
    failedRecordForCch: string
}
